spring:
  profiles:
    active: test
---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dev?useSSL=false
    username: root
    password: dbpass
---
spring:
  application:
    name: payment-service
  profiles: docker
  redis:
    host: redis
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
  sleuth:
    sampler:
      percentage: 1.0
    traceId128: true
  zipkin:
    base-url: http://zipkin:9411/

server.session.cookie.name: payment-service
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2