spring.profiles.active: development
---

spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.100}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
---

spring:
  profiles: docker
  application:
    name: inventory-service
  data.neo4j:
    uri: http://user:password@neo4j:7474
  neo4j:
    host: neo4j
    port: 7474
    username: neo4j
    password: neo4j
  sleuth:
    sampler:
      percentage: 1.0
    traceId128: true
  zipkin:
    base-url: http://zipkin:9411/
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

server.session.cookie.name: inventory-service

---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false